version: '3.3'

services:
  polar_mysql_catalog:
    image: mysql:8.0
    container_name: polar_mysql_catalog
    restart: always
    environment:
      MYSQL_DATABASE: 'polardb_catalog'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql:z

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - '9090:8080'
    depends_on:
      - db

volumes:
  my-db: