version: '2.1'

services:
  polar_mysql_catalog:
    image: mysql:8.0
    container_name: polar_mysql_catalog
    restart: always
    environment:
      MYSQL_DATABASE: 'polardb_catalog'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./polar_mysql_db:/var/lib/mysql:z
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h",  "localhost"]
      timeout: 45s
      interval: 10s
      retries: 10
    networks:
      - catalog-network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - '9090:8080'
    depends_on:
      - polar_mysql_catalog
    networks:
      - catalog-network

  config-service:
    build: ./config-service
    image: ernestoacostacuba/config-service:0.0.1-SNAPSHOT
    container_name: config-service
    ports:
      - '8888:8888'
    networks:
      - catalog-network

  catalog-service:
    image: ernestoacostacuba/catalog-service:0.0.1-SNAPSHOT
    container_name: catalog-service
    environment:
      BPL_DEBUG_ENABLED: true   # Activates the JVM configuration for accepting debug connections
      BPL_DEBUG_PORT: 8001      # Debug connections are accepted via a socket on port 8001
      BPL_JVM_THREAD_COUNT: 50
      SPRING_DATASOURCE_URL: jdbc:mysql://polar_mysql_catalog:3306/polardb_catalog?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_CLOUD_CONFIG_URI: http://config-service:8888
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '8001:8001' # The port where the JVM will listen for debug connections
      - '9001:9001'
    depends_on:
      polar_mysql_catalog:
        condition: service_healthy
    networks:
      - catalog-network

volumes:
  my-db:

networks:
  catalog-network: