version: '3.3'

services:
  polar_mysql_catalog:
    image: mysql:8.0
    container_name: polar_mysql_catalog
    restart: always
    environment:
      MYSQL_DATABASE: 'polardb_catalog'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql:z
    networks:
      - catalog-network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - '9090:8080'
    depends_on:
      - polar_mysql_catalog
    networks:
      - catalog-network

  catalog-service:
    image: ernestoacostacuba/catalog-service:0.0.1-SNAPSHOT
    container_name: catalog-service
    environment:
      BPL_DEBUG_ENABLED: true   # Activates the JVM configuration for accepting debug connections
      BPL_DEBUG_PORT: 8001      # Debug connections are accepted via a socket on port 8001
      BPL_JVM_THREAD_COUNT: 50
      SPRING_DATASOURCE_URL: jdbc:mysql://polar_mysql_catalog:3306/polardb_catalog?useSSL=false&allowPublicKeyRetrieval=true
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      WAIT_HOSTS: polar_mysql_catalog:3306
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_CONNECT_TIMEOUT: 30
    ports:
      - '8001:8001' # The port where the JVM will listen for debug connections
      - '9001:9001'
    depends_on:
      - polar_mysql_catalog
    command: sh -c "/wait && java -Djava.security.egd=file:/dev/./urandom -jar /catalog-service.jar"
    networks:
      - catalog-network

volumes:
  my-db:

networks:
  catalog-network: