apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: catalog-service
build:
  artifacts:
    - image: ernestoacostacuba/catalog-service
      buildpacks:
        builder: gcr.io/paketo-buildpacks/builder:base
        env:
          - BP_JVM_VERSION=11.*
  local:
    push: false
deploy:
  kubectl:
    manifests:
      - k8s/deployment.yml
