apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: ernestoacostacuba/catalog-service
          imagePullPolicy: IfNotPresent
          args: ["--spring.profiles.active=mysqldev"]
          lifecycle:
            preStop:  # Makes K8 wait 5 seconds before sending the SIGTERM signal to the Pod
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9001
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
            - name: DB_HOST
              value: polar-mysql
            - name: DB_NAME
              value: polardb_catalog
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://polar-mysql:3306/polardb_catalog?useSSL=false&allowPublicKeyRetrieval=true
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: catalog-service-conf
                  key: db_username
            - name: DB_PASSWORD
              value: TXlzcWwzMjFDYXRhbG9n
#              valueFrom:
#                secretKeyRef:
#                  name: catalog-service-creds
#                  key: catalog_mysql_password
---

